# Generated by Django 3.1.7 on 2021-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('university', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0, editable=False)),
                ('totalLesson', models.IntegerField(default=0, editable=False)),
                ('totalComment', models.IntegerField(default=0, editable=False)),
                ('lessonPrice', models.IntegerField(default=0)),
                ('about', models.TextField()),
                ('balance', models.FloatField(default=0, editable=False)),
                ('lectures', models.ManyToManyField(blank=True, to='lecture.Lecture')),
            ],
        ),
    ]
