# Generated by Django 3.1.7 on 2021-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20210427_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
