# Generated by Django 3.2.2 on 2021-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructorStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='studentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
