# Generated by Django 3.2.2 on 2021-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
