# Generated by Django 3.2.2 on 2021-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instructorStatus',
            field=models.IntegerField(default=0),
        ),
    ]
