# Generated by Django 3.2.2 on 2021-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_lesson_instructorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='studentStatus',
            field=models.IntegerField(default=0),
        ),
    ]
