# Generated by Django 3.1.7 on 2021-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('credit', models.FloatField(default=0, editable=False)),
            ],
        ),
    ]
