# Generated by Django 3.1.7 on 2021-03-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('university', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('lessonPrice', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('about', models.TextField()),
                ('lessons', models.ManyToManyField(to='lecture.Lecture')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
