# Generated by Django 3.2.2 on 2021-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
